/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventIdRouteRouteImport } from './routes/$eventId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinEventIdRouteImport } from './routes/join/$eventId'
import { Route as EventIdNewBillRouteImport } from './routes/$eventId/newBill'
import { Route as EventIdBillsTableRouteImport } from './routes/$eventId/billsTable'
import { Route as EventIdBillhistoryRouteImport } from './routes/$eventId/billhistory'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRouteRoute = EventIdRouteRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinEventIdRoute = JoinEventIdRouteImport.update({
  id: '/join/$eventId',
  path: '/join/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdNewBillRoute = EventIdNewBillRouteImport.update({
  id: '/newBill',
  path: '/newBill',
  getParentRoute: () => EventIdRouteRoute,
} as any)
const EventIdBillsTableRoute = EventIdBillsTableRouteImport.update({
  id: '/billsTable',
  path: '/billsTable',
  getParentRoute: () => EventIdRouteRoute,
} as any)
const EventIdBillhistoryRoute = EventIdBillhistoryRouteImport.update({
  id: '/billhistory',
  path: '/billhistory',
  getParentRoute: () => EventIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$eventId': typeof EventIdRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/$eventId/billhistory': typeof EventIdBillhistoryRoute
  '/$eventId/billsTable': typeof EventIdBillsTableRoute
  '/$eventId/newBill': typeof EventIdNewBillRoute
  '/join/$eventId': typeof JoinEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$eventId': typeof EventIdRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/$eventId/billhistory': typeof EventIdBillhistoryRoute
  '/$eventId/billsTable': typeof EventIdBillsTableRoute
  '/$eventId/newBill': typeof EventIdNewBillRoute
  '/join/$eventId': typeof JoinEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$eventId': typeof EventIdRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/$eventId/billhistory': typeof EventIdBillhistoryRoute
  '/$eventId/billsTable': typeof EventIdBillsTableRoute
  '/$eventId/newBill': typeof EventIdNewBillRoute
  '/join/$eventId': typeof JoinEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$eventId'
    | '/login'
    | '/signup'
    | '/user'
    | '/$eventId/billhistory'
    | '/$eventId/billsTable'
    | '/$eventId/newBill'
    | '/join/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$eventId'
    | '/login'
    | '/signup'
    | '/user'
    | '/$eventId/billhistory'
    | '/$eventId/billsTable'
    | '/$eventId/newBill'
    | '/join/$eventId'
  id:
    | '__root__'
    | '/'
    | '/$eventId'
    | '/login'
    | '/signup'
    | '/user'
    | '/$eventId/billhistory'
    | '/$eventId/billsTable'
    | '/$eventId/newBill'
    | '/join/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventIdRouteRoute: typeof EventIdRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UserRoute: typeof UserRoute
  JoinEventIdRoute: typeof JoinEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$eventId': {
      id: '/$eventId'
      path: '/$eventId'
      fullPath: '/$eventId'
      preLoaderRoute: typeof EventIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$eventId': {
      id: '/join/$eventId'
      path: '/join/$eventId'
      fullPath: '/join/$eventId'
      preLoaderRoute: typeof JoinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$eventId/newBill': {
      id: '/$eventId/newBill'
      path: '/newBill'
      fullPath: '/$eventId/newBill'
      preLoaderRoute: typeof EventIdNewBillRouteImport
      parentRoute: typeof EventIdRouteRoute
    }
    '/$eventId/billsTable': {
      id: '/$eventId/billsTable'
      path: '/billsTable'
      fullPath: '/$eventId/billsTable'
      preLoaderRoute: typeof EventIdBillsTableRouteImport
      parentRoute: typeof EventIdRouteRoute
    }
    '/$eventId/billhistory': {
      id: '/$eventId/billhistory'
      path: '/billhistory'
      fullPath: '/$eventId/billhistory'
      preLoaderRoute: typeof EventIdBillhistoryRouteImport
      parentRoute: typeof EventIdRouteRoute
    }
  }
}

interface EventIdRouteRouteChildren {
  EventIdBillhistoryRoute: typeof EventIdBillhistoryRoute
  EventIdBillsTableRoute: typeof EventIdBillsTableRoute
  EventIdNewBillRoute: typeof EventIdNewBillRoute
}

const EventIdRouteRouteChildren: EventIdRouteRouteChildren = {
  EventIdBillhistoryRoute: EventIdBillhistoryRoute,
  EventIdBillsTableRoute: EventIdBillsTableRoute,
  EventIdNewBillRoute: EventIdNewBillRoute,
}

const EventIdRouteRouteWithChildren = EventIdRouteRoute._addFileChildren(
  EventIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventIdRouteRoute: EventIdRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UserRoute: UserRoute,
  JoinEventIdRoute: JoinEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
